
server:
  port: 8082

#ConfigServer
#MySql DB
#Database configuration
spring:
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  datasource:
    name: order_db
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Niraj@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true


management:
  tracing:
    sampling:
      probability: 1.0

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    # Whether the Eureka client should register itself with Eureka Server
#    register-with-eureka: true
#    # Whether the Eureka client should fetch registry information from Eureka Server
#    fetch-registry: true
#    # List of Eureka server service URLs for registration and fetching registry information
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}

## Above all Configuration for Eureka client gets imported from config server:
#spring:
#  application:
#    name: Order-Service
#  config:
#    import: configserver:http://localhost:9296
